# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-01 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_auto_20180701_1942'),
        ('profiles', '0002_auto_20180630_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField(default='http://i0.wp.com/cdn.techgyd.com/save-whatsapp-profile-picture-image3.jpg')),
                ('about', models.CharField(default=None, max_length=4096)),
                ('rating', models.FloatField(default=0)),
                ('creation_date', models.DateField()),
                ('profession', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='bots.Profession')),
            ],
        ),
        migrations.RenameModel(
            old_name='Bot_Profile',
            new_name='BotProfile',
        ),
        migrations.RenameModel(
            old_name='Group_Profile',
            new_name='GroupProfile',
        ),
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='UserProfile',
        ),
    ]
