# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-03 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180701_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionprofile',
            name='profession',
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='about',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='about',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='ProfessionProfile',
        ),
    ]
