# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20180703_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='botprofile',
            name='color',
            field=models.CharField(default='90EE90', max_length=8),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='color',
            field=models.CharField(default='fafad2', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='color',
            field=models.CharField(default='00bfff', max_length=8),
        ),
    ]
