# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180716_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botprofile',
            name='bot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bot_profile', to='bots.Bot'),
        ),
        migrations.AlterField(
            model_name='botprofile',
            name='icon',
            field=models.CharField(default='fas fa-stroopwafel', max_length=64),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='icon',
            field=models.CharField(default='fas fa-stroopwafel', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.CharField(default='fas fa-stroopwafel', max_length=64),
        ),
    ]
