# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-16 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20180716_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botprofile',
            name='icon',
            field=models.CharField(default='fas fa-android', max_length=64),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='icon',
            field=models.CharField(default='fas fa-users', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.CharField(default='fas fa-user', max_length=64),
        ),
    ]
