# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-12 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20180723_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botprofile',
            options={'verbose_name': 'Bot Profile', 'verbose_name_plural': 'Bot Profiles'},
        ),
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'verbose_name': 'Group Profile', 'verbose_name_plural': 'Group Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
