# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-30 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='issued_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
