# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-01 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0003_auto_20180630_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('public_key', models.CharField(max_length=4096)),
                ('public_key_expiry', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bot',
            name='group',
        ),
        migrations.AddField(
            model_name='bot',
            name='profession',
            field=models.ManyToManyField(to='bots.Profession'),
        ),
        migrations.AddField(
            model_name='permit',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.Profession'),
        ),
    ]
