# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-01 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_auto_20180701_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bots.Bot'),
        ),
    ]
