# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-01 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_auto_20180701_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='public_key_expiry',
        ),
    ]
