# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-01 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_auto_20180701_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='code',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profession',
            name='code',
            field=models.CharField(default='', max_length=128),
        ),
    ]
