# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-03 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_auto_20180703_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='profession',
        ),
    ]
