# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-03 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('bots', '0009_remove_bot_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='profession',
            field=models.ManyToManyField(to='library.Profession'),
        ),
    ]
