# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-06 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_bot_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
