# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-07 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_bot_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
