# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_bot_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='accept_appointment',
            field=models.BooleanField(default=True),
        ),
    ]
