# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-26 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_bot_accept_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='connection_code',
            field=models.CharField(default='000000', max_length=16),
        ),
    ]
