# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-25 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0018_auto_20180825_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='code',
            field=models.CharField(default='BOT-0829', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='code',
            field=models.CharField(default='RUL-1968', max_length=8, unique=True),
        ),
    ]
