# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-25 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0019_auto_20180825_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='code',
        ),
    ]
